import axios from 'axios';

const N8N_EMAIL_WEBHOOK = process.env.N8N_EMAIL_WEBHOOK;

export async function sendResultEmail({ to, businessName, businessType, jobId, baseUrl, designs, weaknesses, features, contentGaps }) {
    const proposalUrl = `${baseUrl}/output/${jobId}/proposal.html`;
    const designLinks = designs.map(d =>
        `<li><a href="${baseUrl}/output/${jobId}/${d.dir}/index.html" style="color:#2563eb">Design ${d.index}: ${d.name}</a> — ${d.palette.name} palette</li>`
    ).join('');

    const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; }
  .header { background: #1e293b; color: white; padding: 24px; border-radius: 8px 8px 0 0; }
  .body { background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; }
  .cta { display: inline-block; background: #2563eb; color: white !important; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold; margin: 16px 0; }
  ul { padding-left: 20px; } li { margin: 6px 0; }
  .section { background: white; border-radius: 6px; padding: 16px; margin: 12px 0; border: 1px solid #e2e8f0; }
  h3 { margin: 0 0 8px; color: #1e293b; }
</style></head>
<body>
  <div class="header">
    <h2 style="margin:0">🎨 Webpitch — New Proposal Ready</h2>
    <p style="margin:8px 0 0;opacity:0.8">${businessName} · ${businessType}</p>
  </div>
  <div class="body">
    <p>Your website analysis and redesign proposal for <strong>${businessName}</strong> is ready.</p>
    <a href="${proposalUrl}" class="cta">View Full Proposal →</a>
    <div class="section">
      <h3>📐 3 Design Proposals (4 pages each)</h3>
      <ul>${designLinks}</ul>
    </div>
    <div class="section">
      <h3>🔍 Key Opportunities Found</h3>
      <ul>${weaknesses.map(w => `<li>${w}</li>`).join('')}</ul>
    </div>
    <div class="section">
      <h3>⭐ Recommended Features</h3>
      <ul>${features.map(f => `<li>${f}</li>`).join('')}</ul>
    </div>
    <div class="section">
      <h3>📝 Content Client Needs to Provide</h3>
      <ul>${contentGaps.map(g => `<li>${g}</li>`).join('')}</ul>
    </div>
    <p style="color:#64748b;font-size:13px;margin-top:24px">Job ID: ${jobId} · Generated by Webpitch</p>
  </div>
</body>
</html>`;

    await axios.post(N8N_EMAIL_WEBHOOK, { to, businessName, jobId, html }, {
        headers: { 'Content-Type': 'application/json' },
        timeout: 15000,
    });
}
